### ISSUE TITLE
Generated File Errors

### ISSUE THREAD

**Issue by jonnyfux** [ForbesLindesay/typescript-json-validator#42]
I have quite a few problems using the generated file: 
I run `npx typescript-json-validator src/CustomApp.ts ICustomApp`

Which generated this file 

`import {inspect} from 'util';  
import Ajv = require('ajv');  // 1 
import ICustomApp from './CustomApp'; // 2 
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true}); // 1, 3

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {ICustomApp};

import Ajv = require('ajv')
...
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'> // 4
export const isICustomApp = ajv.compile(ICustomAppSchema) as ValidateFunction<ICustomApp>;  
export default function validate(value: unknown): ICustomApp {  
  if (isICustomApp(value)) {  
    return value;  
  } else {  
    throw new Error(  
      ajv.errorsText(isICustomApp.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'ICustomApp'}) +  
      '\n\n' +  
      inspect(value),  
    );  
  }  
}`

This yields those errors: 

1. This expression is not constructable.
  Type 'typeof import("/web/interfaces/node_modules/ajv/dist/ajv")' has no construct signatures.ts(2351)
2. Module '".../src/CustomApp"' has no default export

I can fix 2 with changing it to `import {ICustomApp} from './CustomApp'; and 
1 with import Ajv from "ajv". But this results in the following two new errors: 

3. `Argument of type '{ allErrors: true; coerceTypes: false; format: string; nullable: boolean; unicode: true; uniqueItems: boolean; useDefaults: true; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and '"format"' does not exist in type 'Options'.`
`

4.  `Ajv' only refers to a type, but is being used as a namespace here.ts(2702)
Exported type alias 'ValidateFunction' has or is using private name 'Ajv'`

3 Can be fixed with removing `"format":"fast","nullable":true, "uniqueItems":true,`

4 Can be fixed only when changing the import back to `import Ajv = require('ajv');` which again triggers error 1.

Am I doing something wrong or is the tool generating wrong files?

**Comment by jen-hoang** [comment]
I also had an issue with "format": "fast","nullable": true, "uniqueItems": true, and when I removed them, they worked fine.
Can you post your code in CustomApp.ts. Based on the error message, you may not have export default.
This is an example of my code. It has export default of the interface
![image](https://user-images.githubusercontent.com/55661073/111107852-e43d6100-8514-11eb-8ee6-3bbe82b8ddcd.png)

**Comment by jonnyfux** [comment]
> I also had an issue with "format": "fast","nullable": true, "uniqueItems": true, and when I removed them, they worked fine.
> Can you post your code in CustomApp.ts. Based on the error message, you may not have export default.
> This is an example of my code. It has export default of the interface
> ![image](https://user-images.githubusercontent.com/55661073/111107852-e43d6100-8514-11eb-8ee6-3bbe82b8ddcd.png)

Yes you are correct, it fixes my second error and recognizes it automatically. But my main issue **is the correct import of Ajv**. Either way I try (`import Ajv = require('ajv');` or `import Ajv from "ajv"`) it always results in error 1 or 4....

**Comment by jen-hoang** [comment]
Did you install ajv in the project? I guess it may be the issue.

**Comment by somay** [comment]
I solved this issue by downgrading ajv to 6.12.0, which appears on this project's yarn.lock .

https://github.com/ForbesLindesay/typescript-json-validator/blob/master/yarn.lock#L215

**Comment by jonnyfux** [comment]
> I solved this issue by downgrading ajv to 6.12.0, which appears on this project's yarn.lock .
> 
> https://github.com/ForbesLindesay/typescript-json-validator/blob/master/yarn.lock#L215

Awesome, thank you very much. That resolved all issues!
